const DEFAULT_CONTACT = {
  clinicName: "Dog Mitra",
  phone: "+91 85903 24142",
  whatsapp: "+91 85903 24142",
  email: "anoopkrishnan211@gmail.com",
  address: {
    line1: "Shop Number 14",
    line2: "Amar Mohini Garden, Ujjain Road, Near Abhinav Hotel",
    city: "Dewas",
    state: "Madhya Pradesh",
    pincode: "455001",
    country: "IN",
  },
  googleMapsLink: "https://maps.app.goo.gl/JwNZ55GysRrY5hSs5",
  latitude: 22.9667,
  longitude: 76.0667,
  clinicHours: [
    { day: "Monday", open: "09:00 AM", close: "06:00 PM", closed: false },
    { day: "Tuesday", open: "09:00 AM", close: "06:00 PM", closed: false },
    { day: "Wednesday", open: "09:00 AM", close: "06:00 PM", closed: false },
    { day: "Thursday", open: "09:00 AM", close: "06:00 PM", closed: false },
    { day: "Friday", open: "09:00 AM", close: "06:00 PM", closed: false },
    { day: "Saturday", open: "09:00 AM", close: "06:00 PM", closed: false },
    { day: "Sunday", open: "", close: "", closed: true },
  ],
  emergencyHours: "Available 24 Hours, 7 Days a Week",
  emergencyPhone: "+91 85903 24142",
  parkingInfo: "",
  socialLinks: [],
  active: true,
};

const DEFAULT_SITE = {
  siteName: "Dog Mitra",
  logoUrl: "/assets/dog-mitra-logo.png",
  faviconUrl: "/assets/dog-mitra-logo.png",
  primaryColor: "#1f6b4f",
  secondaryColor: "#ffffff",
  accentColor: "#f0b44c",
  homepageHeroTitle: "Compassionate veterinary care for dogs, pets, and families in Dewas.",
  homepageHeroSubtitle: "Clinic consultations, home visits, preventive care, genuine pet products, and reliable support from one trusted team.",
  doctor: {
    name: "Dr. Sanjeev Kumre",
    bio: "Dr. Sanjeev Kumre leads Dog Mitra with a focus on dog wellness, preventive care, vaccination guidance, everyday illness support, and clear advice for pet parents.",
    specialization: "Dog consultation, vaccination, wellness and home care",
    languages: "English, Hindi",
    timings: "Call or WhatsApp for today's availability",
  },
  bookAppointmentCta: "Book Appointment",
  exploreShopCta: "Explore Shop",
  footerNote: "Emergency veterinary assistance available 24/7.",
  maintenanceMode: false,
  enabledLanguages: ["en", "hi"],
  languageDefault: "en",
  businessHours: {
    display: "Monday - Saturday",
    open: "09:00 AM",
    close: "06:00 PM",
    emergencyLabel: "Emergency Veterinary Assistance",
    emergencyHours: "Available 24 Hours, 7 Days a Week",
  },
  contact: {
    phone: "+91 85903 24142",
    whatsapp: "+91 85903 24142",
    email: "anoopkrishnan211@gmail.com",
  },
  branding: {
    logoUrl: "/assets/dog-mitra-logo.png",
    faviconUrl: "/assets/dog-mitra-logo.png",
  },
  socialLinks: {
    instagram: "",
    facebook: "",
    youtube: "",
    linkedin: "",
    googleBusiness: "",
  },
  payment: {
    method: "UPI",
    upiId: "8590324142@upi",
    qrCodeUrl: "",
    paymentScreenshotUrl: "",
    approvalRequired: true,
    razorpayEnabled: false,
  },
  smtp: {
    host: "",
    port: 587,
    username: "",
    password: "",
    senderName: "Dog Mitra",
    senderEmail: "anoopkrishnan211@gmail.com",
  },
  analytics: {
    ga4: "",
    gtm: "",
    metaPixel: "",
    clarity: "",
  },
  seo: {
    title: "Dog Mitra | Veterinary Clinic, Home Visits & Pet Care Store in Dewas",
    description: "Dog Mitra in Dewas offers veterinary consultations, home visits, vaccination care, pet wellness services, genuine pet medicines, and pet care products with UPI payment support.",
    keywords: ["Dog Mitra", "Veterinary Clinic", "Pet Care", "Dewas", "Home Visit"],
    canonicalUrl: "https://dogmitra.in/",
  },
  emergencyContact: "+91 85903 24142",
};

module.exports = { DEFAULT_CONTACT, DEFAULT_SITE };
