const swaggerJsdoc = () => ({
  openapi: "3.0.3",
  info: {
    title: "Dog Mitra API",
    version: "1.0.0",
    description: "Production backend for Dog Mitra",
  },
  servers: [{ url: "/api" }],
  paths: {
    "/health": { get: { summary: "Health check", responses: { 200: { description: "OK" } } } },
    "/auth/login": { post: { summary: "Login", responses: { 200: { description: "JWT issued" } } } },
    "/auth/register-admin": { post: { summary: "Create initial admin", responses: { 201: { description: "Admin created" } } } },
    "/auth/logout": { post: { summary: "Logout" } },
    "/auth/refresh": { post: { summary: "Refresh JWT session" } },
    "/auth/forgot-password": { post: { summary: "Request reset token" } },
    "/auth/reset-password": { post: { summary: "Reset password" } },
    "/auth/change-password": { post: { summary: "Change password" } },
    "/auth/sessions": { get: { summary: "List active sessions" } },
    "/auth/sessions/{id}": { delete: { summary: "Revoke session" } },
    "/staff": { get: { summary: "List staff" }, post: { summary: "Create staff" } },
    "/staff/{id}": { get: { summary: "Get staff" }, patch: { summary: "Update staff" }, delete: { summary: "Delete staff" } },
    "/customers": { get: { summary: "List customers" }, post: { summary: "Create customer" } },
    "/customers/{id}": { get: { summary: "Get customer" }, patch: { summary: "Update customer" }, delete: { summary: "Delete customer" } },
    "/pets": { get: { summary: "List pets" }, post: { summary: "Create pet" } },
    "/pets/{id}": { get: { summary: "Get pet" }, patch: { summary: "Update pet" }, delete: { summary: "Delete pet" } },
    "/appointments": { get: { summary: "List appointments" }, post: { summary: "Create appointment" } },
    "/appointments/{id}": { get: { summary: "Get appointment" }, patch: { summary: "Update appointment" }, delete: { summary: "Delete appointment" } },
    "/products": { get: { summary: "List products" }, post: { summary: "Create product" } },
    "/products/{id}": { get: { summary: "Get product" }, patch: { summary: "Update product" }, delete: { summary: "Delete product" } },
    "/categories": { get: { summary: "List categories" }, post: { summary: "Create category" } },
    "/categories/{id}": { get: { summary: "Get category" }, patch: { summary: "Update category" }, delete: { summary: "Delete category" } },
    "/inventory": { get: { summary: "List inventory" }, post: { summary: "Create inventory record" } },
    "/inventory/{id}": { get: { summary: "Get inventory record" }, patch: { summary: "Update inventory record" }, delete: { summary: "Delete inventory record" } },
    "/orders": { get: { summary: "List orders" }, post: { summary: "Create order" } },
    "/orders/{id}": { get: { summary: "Get order" }, patch: { summary: "Update order" }, delete: { summary: "Delete order" } },
    "/testimonials": { get: { summary: "List testimonials" }, post: { summary: "Create testimonial" } },
    "/testimonials/{id}": { get: { summary: "Get testimonial" }, patch: { summary: "Update testimonial" }, delete: { summary: "Delete testimonial" } },
    "/gallery": { get: { summary: "List gallery items" }, post: { summary: "Create gallery item" } },
    "/gallery/{id}": { get: { summary: "Get gallery item" }, patch: { summary: "Update gallery item" }, delete: { summary: "Delete gallery item" } },
    "/services": { get: { summary: "List services" }, post: { summary: "Create service" } },
    "/services/{id}": { get: { summary: "Get service" }, patch: { summary: "Update service" }, delete: { summary: "Delete service" } },
    "/blog-posts": { get: { summary: "List blog posts" }, post: { summary: "Create blog post" } },
    "/blog-posts/{id}": { get: { summary: "Get blog post" }, patch: { summary: "Update blog post" }, delete: { summary: "Delete blog post" } },
    "/faqs": { get: { summary: "List FAQs" }, post: { summary: "Create FAQ" } },
    "/faqs/{id}": { get: { summary: "Get FAQ" }, patch: { summary: "Update FAQ" }, delete: { summary: "Delete FAQ" } },
    "/contact-information": { get: { summary: "List contact information" }, post: { summary: "Create contact information" } },
    "/contact-information/{id}": { get: { summary: "Get contact information" }, patch: { summary: "Update contact information" }, delete: { summary: "Delete contact information" } },
    "/site-settings": { get: { summary: "List site settings" }, post: { summary: "Create site settings" } },
    "/site-settings/{id}": { get: { summary: "Get site settings" }, patch: { summary: "Update site settings" }, delete: { summary: "Delete site settings" } },
  },
});

module.exports = { swaggerJsdoc };
